# Generated by Django 4.0 on 2021-12-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturistico',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
