# Generated by Django 4.0 on 2021-12-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_alter_pontosturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
