# Generated by Django 4.0 on 2021-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontosturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
