# Generated by Django 4.0 on 2021-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontosturistico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontosturistico',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
