# Generated by Django 4.0 on 2021-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_pontosturistico_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='endereco',
            field=models.ManyToManyField(to='enderecos.Endereco'),
        ),
    ]
