# Generated by Django 4.0 on 2021-12-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0006_pontosturistico_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturistico',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pontosturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
